CREATE DATABASE NewFacultyy
GO
USE NewFacultyy
GO

CREATE TABLE Groups(
Gid INT PRIMARY KEY,
NrOfS INT NOT NULL
)

CREATE TABLE Teachers(
Tid INT PRIMARY KEY IDENTITY,
Name VARCHAR(50),
Age INT DEFAULT 30
)

CREATE TABLE Students(
Sid INT PRIMARY KEY,
Name VARCHAR(50),
Gid INT FOREIGN KEY REFERENCES Groups(Gid)
)

CREATE TABLE Courses(
Sid INT FOREIGN KEY REFERENCES Students(Sid),
Tid INT FOREIGN KEY REFERENCES Teachers(Tid),
CDate DATE,
Credits INT CHECK(Credits = 5 OR Credits = 6), 
CONSTRAINT	pk_Courses PRIMARY KEY(Sid, Tid)
)

CREATE TABLE Tutors(
Tuid INT FOREIGN KEY REFERENCES Groups(Gid),
Name VARCHAR(50), 
CONSTRAINT pk_Tutors PRIMARY KEY(Tuid)
)