SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
BEGIN TRAN 
SELECT * FROM Books 
WAITFOR DELAY '00:00:15' 
SELECT * FROM Books 
COMMIT TRAN

SET TRANSACTION ISOLATION LEVEL READ COMMITTED 
BEGIN TRAN 
SELECT * FROM Books 
WAITFOR DELAY '00:00:15' 
SELECT * FROM Books 
COMMIT TRAN