SET TRANSACTION ISOLATION LEVEL REPEATABLE READ 
BEGIN TRAN 
SELECT * FROM Books 
WAITFOR DELAY '00:00:15' 
SELECT * FROM Books 
COMMIT TRAN

select * from Books 
delete from Books 
where title='At the end of the world' 
select * from Books

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
BEGIN TRAN 
SELECT * FROM Books 
WAITFOR DELAY '00:00:15' 
SELECT * FROM Books 
COMMIT TRAN